
services:
  velocitygames:
    image: velocitygames-wordpress
    build: .
    container_name: velocitygames-wordpress
    restart: always
    ports:
      - "4380:80"
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - sigma-net
    depends_on:
      - velocitygames-db

  velocitygames-db:
    image: mariadb:10.6
    container_name: velocitygames-db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:4354:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sigma-net

volumes:
  db_data:

networks:
  sigma-net:
    external: true
